import { Button, Chip, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, IconButton, Tooltip } from '@mui/material';
import { ArrowForward, MoreHoriz, PlayArrow, VideocamOutlined, OpenInFull, CenterFocusStrong } from '@mui/icons-material';
import { Link } from '@tanstack/react-router';
import gate from '@/assets/gate-camera.jpg';
import { recent, type Evidence } from '@/lib/visiontrace/data';
export function PageHeading({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <div className="page-heading"><div><h1>{title}</h1><p className="subtitle">{subtitle}</p></div>{action}</div>}
export function SectionHeading({title,action}:{title:string;action?:React.ReactNode}){return <div className="section-heading"><h2>{title}</h2>{action}</div>}
export function Status({status}:{status:string}){return <Chip size="small" label={status} color={['Verified','Indexed','Online','Ready','Open','Connected'].includes(status)?'success':status==='Failed'?'error':'warning'} icon={status==='Verified'?<CenterFocusStrong sx={{fontSize:'12px!important'}}/>:undefined}/>}
export function RecentTable({all=false}:{all?:boolean}){return <TableContainer component={Paper} variant="outlined" sx={{borderRadius:1}}><Table sx={{minWidth:600}}><TableHead><TableRow>{['Search query','Camera','Timestamp','Confidence','Status'].map(x=><TableCell key={x}>{x}</TableCell>)}<TableCell/></TableRow></TableHead><TableBody>{recent.slice(0,all?5:3).map(row=><TableRow key={row.query} hover><TableCell sx={{fontWeight:500}}>“{row.query}”</TableCell><TableCell><span style={{display:'flex',alignItems:'center',gap:5}}><VideocamOutlined sx={{fontSize:13,color:'var(--muted-foreground)'}}/>{row.camera}</span></TableCell><TableCell sx={{color:'text.secondary'}}>{row.time}</TableCell><TableCell><span style={{display:'flex',gap:7,alignItems:'center'}}><span style={{width:32,height:4,background:'var(--muted)',borderRadius:4}}><span style={{display:'block',width:`${row.confidence}%`,height:4,borderRadius:4,background:'var(--success)'}}/></span>{row.confidence}%</span></TableCell><TableCell><Status status={row.status}/></TableCell><TableCell><Tooltip title="Search this query"><IconButton component={Link} to="/ai-search" size="small"><ArrowForward sx={{fontSize:16}}/></IconButton></Tooltip></TableCell></TableRow>)}</TableBody></Table></TableContainer>}
export function CameraPreview({evidence,boxes=false,onOpen}:{evidence?:Evidence;boxes?:boolean;onOpen?:()=>void}){const image=evidence?.thumbnail_url??(!evidence?gate:undefined);return <div className="camera-preview">{image?<img src={image} width={1280} height={720} alt={`${evidence?.camera_name??'Main Gate'} security camera still`} loading="lazy"/>:<div style={{height:'100%',display:'grid',placeContent:'center',textAlign:'center',color:'var(--sidebar-text)',fontSize:12}}><VideocamOutlined sx={{fontSize:35,margin:'auto',mb:1}}/>No thumbnail available</div>}<div className="camera-overlay"><span style={{display:'flex',alignItems:'center',gap:6}}><span className="dot"/>{evidence?.camera_id??'CAM-03'} · {evidence?.camera_name??'Main Gate'}</span><span>{evidence?.timestamp??'10:42:17'}</span></div>{(evidence?.sample||!evidence)&&<span className="sample-label">SAMPLE FOOTAGE</span>}{boxes&&image&&(evidence?.sample||evidence?.bounding_box)&&<div className="bounding-box" style={evidence?.bounding_box?{left:`${evidence.bounding_box.x*100}%`,top:`${evidence.bounding_box.y*100}%`,width:`${evidence.bounding_box.width*100}%`,height:`${evidence.bounding_box.height*100}%`}:undefined}><span>{evidence?.objects.join(' · ')??'Car · 94%'}</span></div>}<div className="camera-bottom"><span style={{display:'flex',alignItems:'center',gap:7}}><VideocamOutlined sx={{fontSize:15}}/>{evidence?.location??'North entrance'}</span>{onOpen?<Tooltip title="Open evidence"><IconButton size="small" onClick={onOpen} sx={{color:'var(--card)'}}><OpenInFull sx={{fontSize:16}}/></IconButton></Tooltip>:<span style={{fontSize:9}}>RECORDED</span>}</div></div>}
