import { Button, Chip } from '@mui/material';
import { ArrowForward, PlayArrow, UploadFile, ManageSearch, VerifiedOutlined, CenterFocusStrong } from '@mui/icons-material';
import { Link } from '@tanstack/react-router';
import { useSession } from './Session';
import gate from '@/assets/gate-camera.jpg';

export function Home() {
 const {user,signIn}=useSession();
 return <><section className="home-hero"><img className="hero-footage" src={gate} alt="Sample CCTV view of an entrance and vehicle"/><div className="hero-shade"/><div className="hero-copy"><div className="hero-eyebrow"><span className="dot"/> VIDEO INTELLIGENCE, IN FOCUS</div><h1>VisionTrace <span>AI</span></h1><p className="hero-tagline">Search. Trace. Verify.</p><p className="hero-description">Turn hours of CCTV footage into moments you can verify. Find the camera, the timestamp, and the evidence that matters.</p><div className="hero-actions">{user?<Button component={Link} to="/dashboard" variant="contained" endIcon={<ArrowForward/>}>Open dashboard</Button>:<Button onClick={()=>signIn('/dashboard')} variant="contained" endIcon={<ArrowForward/>}>Enter workspace</Button>}<Button component={Link} to="/dashboard" variant="outlined" startIcon={<PlayArrow/>}>Explore sample demo</Button></div></div><div className="hero-camera"><span>CAM-03 · MAIN GATE</span><Chip label="Sample footage" size="small"/></div><div className="hero-caption"><CenterFocusStrong/> Grounded in the footage. Built for the operator.</div></section><section className="public-section"><div className="public-section-heading"><div><span className="eyebrow">FROM FOOTAGE TO EVIDENCE</span><h2>A clearer path to the right moment.</h2></div><Button component={Link} to="/about" endIcon={<ArrowForward/>}>About VisionTrace</Button></div><div className="workflow-grid">{[{icon:UploadFile,n:'01',title:'Bring your footage',text:'Your recordings, organized by camera, location, and time.'},{icon:ManageSearch,n:'02',title:'Ask your question',text:'Search across cameras in natural language with your connected AWS service.'},{icon:VerifiedOutlined,n:'03',title:'Verify the evidence',text:'Review matching clips, timestamps, and confidence before drawing conclusions.'}].map(s=><article key={s.n}><div className="workflow-top"><s.icon/><span>{s.n}</span></div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section></>;
}
export function About(){const {signIn,user}=useSession();return <><section className="about-intro public-section"><span className="eyebrow">ABOUT VISIONTRACE</span><h1>Evidence first.<br/>Every investigation.</h1><p className="about-lead">VisionTrace AI gives security operators a focused place to organize recordings, search footage, and review the moments behind a match.</p></section><section className="about-image"><img src={gate} alt="Sample surveillance footage of the main gate"/><Chip label="Sample footage · CAM-03"/></section><section className="public-section about-details"><div><span className="eyebrow">SEARCH. TRACE. VERIFY.</span><h2>Context makes the difference.</h2></div><div><p>A result is only useful when you can trace it back to its source. VisionTrace brings camera identity, recording time, detected objects, confidence, and matching clips into one evidence review.</p><h3>Your footage. Your workspace.</h3><p>Sign in to upload private recordings and save investigations. The sample demo is separate from your records and clearly marked.</p><h3>Connected intelligence, not simulated certainty.</h3><p>Computer vision and AI processing run on your external AWS service. VisionTrace is the operator interface. Sample detections demonstrate the review experience; they are not live intelligence.</p>{user?<Button component={Link} to="/dashboard" variant="contained" endIcon={<ArrowForward/>}>Open dashboard</Button>:<Button onClick={()=>signIn('/dashboard')} variant="contained" endIcon={<ArrowForward/>}>Enter workspace</Button>}</div></section></>}
