/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiSearchRouteImport } from './routes/ai-search'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventLibraryRouteImport } from './routes/event-library'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as ObjectTrackingRouteImport } from './routes/object-tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpatialMemoryRouteImport } from './routes/spatial-memory'
import { Route as VideoIntelligenceRouteImport } from './routes/video-intelligence'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchRoute = AiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventLibraryRoute = EventLibraryRouteImport.update({
  id: '/event-library',
  path: '/event-library',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectTrackingRoute = ObjectTrackingRouteImport.update({
  id: '/object-tracking',
  path: '/object-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpatialMemoryRoute = SpatialMemoryRouteImport.update({
  id: '/spatial-memory',
  path: '/spatial-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIntelligenceRoute = VideoIntelligenceRouteImport.update({
  id: '/video-intelligence',
  path: '/video-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-search': typeof AiSearchRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cameras': typeof CamerasRoute
  '/dashboard': typeof DashboardRoute
  '/event-library': typeof EventLibraryRoute
  '/investigations': typeof InvestigationsRoute
  '/object-tracking': typeof ObjectTrackingRoute
  '/settings': typeof SettingsRoute
  '/spatial-memory': typeof SpatialMemoryRoute
  '/video-intelligence': typeof VideoIntelligenceRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-search': typeof AiSearchRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cameras': typeof CamerasRoute
  '/dashboard': typeof DashboardRoute
  '/event-library': typeof EventLibraryRoute
  '/investigations': typeof InvestigationsRoute
  '/object-tracking': typeof ObjectTrackingRoute
  '/settings': typeof SettingsRoute
  '/spatial-memory': typeof SpatialMemoryRoute
  '/video-intelligence': typeof VideoIntelligenceRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-search': typeof AiSearchRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cameras': typeof CamerasRoute
  '/dashboard': typeof DashboardRoute
  '/event-library': typeof EventLibraryRoute
  '/investigations': typeof InvestigationsRoute
  '/object-tracking': typeof ObjectTrackingRoute
  '/settings': typeof SettingsRoute
  '/spatial-memory': typeof SpatialMemoryRoute
  '/video-intelligence': typeof VideoIntelligenceRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-search'
    | '/alerts'
    | '/analytics'
    | '/cameras'
    | '/dashboard'
    | '/event-library'
    | '/investigations'
    | '/object-tracking'
    | '/settings'
    | '/spatial-memory'
    | '/video-intelligence'
    | '/api/public/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-search'
    | '/alerts'
    | '/analytics'
    | '/cameras'
    | '/dashboard'
    | '/event-library'
    | '/investigations'
    | '/object-tracking'
    | '/settings'
    | '/spatial-memory'
    | '/video-intelligence'
    | '/api/public/transcribe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-search'
    | '/alerts'
    | '/analytics'
    | '/cameras'
    | '/dashboard'
    | '/event-library'
    | '/investigations'
    | '/object-tracking'
    | '/settings'
    | '/spatial-memory'
    | '/video-intelligence'
    | '/api/public/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSearchRoute: typeof AiSearchRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CamerasRoute: typeof CamerasRoute
  DashboardRoute: typeof DashboardRoute
  EventLibraryRoute: typeof EventLibraryRoute
  InvestigationsRoute: typeof InvestigationsRoute
  ObjectTrackingRoute: typeof ObjectTrackingRoute
  SettingsRoute: typeof SettingsRoute
  SpatialMemoryRoute: typeof SpatialMemoryRoute
  VideoIntelligenceRoute: typeof VideoIntelligenceRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search': {
      id: '/ai-search'
      path: '/ai-search'
      fullPath: '/ai-search'
      preLoaderRoute: typeof AiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-library': {
      id: '/event-library'
      path: '/event-library'
      fullPath: '/event-library'
      preLoaderRoute: typeof EventLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object-tracking': {
      id: '/object-tracking'
      path: '/object-tracking'
      fullPath: '/object-tracking'
      preLoaderRoute: typeof ObjectTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spatial-memory': {
      id: '/spatial-memory'
      path: '/spatial-memory'
      fullPath: '/spatial-memory'
      preLoaderRoute: typeof SpatialMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-intelligence': {
      id: '/video-intelligence'
      path: '/video-intelligence'
      fullPath: '/video-intelligence'
      preLoaderRoute: typeof VideoIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSearchRoute: AiSearchRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CamerasRoute: CamerasRoute,
  DashboardRoute: DashboardRoute,
  EventLibraryRoute: EventLibraryRoute,
  InvestigationsRoute: InvestigationsRoute,
  ObjectTrackingRoute: ObjectTrackingRoute,
  SettingsRoute: SettingsRoute,
  SpatialMemoryRoute: SpatialMemoryRoute,
  VideoIntelligenceRoute: VideoIntelligenceRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
